name: Playwright Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Node.js (for Playwright)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Playwright
      run: npx playwright install

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test
